# A docker-compose config for packagist server dependencies
db:
  image: mariadb:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: rootpw
    MYSQL_USER: me
    MYSQL_PASSWORD: mypw
    MYSQL_DATABASE: mydb
redis:
  image: redis
  ports:
    - "6379:6379"
solr:
  build: solr
  ports:
    - "8983:8983"
rabbit:
  image: rabbitmq
  ports:
    - "8080:5672"
